- name: install the mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable the server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install the python dependencies
  ansible.builtin.pip:
    name:
    - pymysql
    - cryptography
    executable: pip3.9

- name: check root password setup or not
  community.mysql.mysql_info:
    login_user: "{{login_user}}"
    login_password: "{{login_password}}"
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: true
  register: mysql_info

- name: print the information
  ansible.builtin.debug:
    msg: "{{mysql_info}}"